# Generated by Django 5.0.2 on 2024-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_signup_confirmpassword_alter_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attandance',
            name='breaktime',
        ),
        migrations.RemoveField(
            model_name='attandance',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='attandance',
            name='exit',
        ),
        migrations.RemoveField(
            model_name='attandance',
            name='userid',
        ),
        migrations.AddField(
            model_name='attandance',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
