# Generated by Django 4.2.6 on 2024-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_attandance_time_alter_attandance_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
