# Generated by Django 5.0.2 on 2024-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_attandance_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attandance',
            name='userid',
        ),
        migrations.AlterField(
            model_name='attandance',
            name='checkin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attandance',
            name='checkout',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
