# Generated by Django 5.0.2 on 2024-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_remove_attandance_userid_alter_attandance_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
